# Generated by Django 5.2 on 2025-04-03 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Электронная почта")),
                ("country", models.CharField(max_length=100, verbose_name="Cтрана")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house_number", models.CharField(max_length=20, verbose_name="Номер дома")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                ("release_date", models.DateField(verbose_name="Дата выхода продукта на рынок")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Задолженность перед поставщиком"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "level",
                    models.IntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "ИП")],
                        editable=False,
                        verbose_name="Уровень иерархии",
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.contacts",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="network.network",
                        verbose_name="Поставщик",
                    ),
                ),
                ("products", models.ManyToManyField(blank=True, to="network.product", verbose_name="Продукты")),
            ],
            options={
                "verbose_name": "Сеть",
                "verbose_name_plural": "Сети",
            },
        ),
    ]
